# Generated by Django 4.0.3 on 2022-03-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_imagerec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerec',
            old_name='image',
            new_name='upload',
        ),
    ]
