# Generated by Django 4.0.3 on 2022-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_image_imagerec_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerec',
            name='upload',
        ),
        migrations.AddField(
            model_name='imagerec',
            name='url',
            field=models.ImageField(default=0, upload_to='', verbose_name='url'),
            preserve_default=False,
        ),
    ]
