# Generated by Django 4.0.3 on 2022-03-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_imagerec_upload_imagerec_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerec',
            old_name='url',
            new_name='upload',
        ),
    ]
