# Generated by Django 4.0.3 on 2022-04-19 11:24

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_url_imagerec_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_post', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='imagerec',
            name='upload',
            field=models.ImageField(upload_to=posts.models.get_file_path),
        ),
    ]
