# Generated by Django 4.0.3 on 2022-07-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVejaBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('content', models.FileField(upload_to='')),
            ],
        ),
    ]
