# Generated by Django 4.0.3 on 2022-07-12 15:31

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsvejabem',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsvejabem',
            name='content',
            field=models.FileField(upload_to=news.models.get_file_path),
        ),
    ]
