# Generated by Django 4.0.3 on 2022-05-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariaveisAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavel', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.CharField(max_length=10)),
                ('valor2', models.CharField(blank=True, max_length=50, null=True)),
                ('valor3', models.CharField(blank=True, max_length=50, null=True)),
                ('valor4', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
