# Generated by Django 4.0.3 on 2022-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_variaveisambiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variaveisambiente',
            name='valor',
        ),
        migrations.AddField(
            model_name='variaveisambiente',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
