# Generated by Django 4.0.3 on 2022-06-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_variaveisambiente_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateadmicao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='datenasc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
